config/routes.rb
WikiApp::Application.routes.draw do
  devise_for :users
  resources :pages 
  root to: "home#index"

end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  belongs_to :page
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.order('name ASC')
  end

  def show
    @page = Page.find(params[:id])
    #@sections = params[:page][:sections].split(", ")
    @sections = @page.sections.split(", ")
    @page.sections = @sections
  end

  def new
    @page = Page.new
  end

  def create 
    #params[:body] = params[:hidden_body]

    @page = Page.new(page_params)
    # @sections = params[:page][:sections].split(", ")
    # @page.sections = @sections
    @page.save

    redirect_to [@page]
    
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    @page.update_attributes(page_params)
    # @sections = params[:page][:sections].split(", ")
    # @page.sections = @sections
    @page.save
  end

  private

  def page_params
    params.require(:page).permit(:name, :sections, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<br/>
<div class='jumbotron other'>
  <h1>Wiskool</h1>
  <p>Want to know all about your and your friends' high schools?</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikiApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class='nav nav-tabs'>
    <li><%= link_to 'All schools', pages_path %></li>
  </ul>
</div>
<%= yield %>

</body>
</html>

app/views/pages/edit.html.erb
<h1>Pages#edit</h1>
<p>Find me in app/views/pages/edit.html.erb</p>

app/views/pages/index.html.erb
<div id = 'box_1'>
  <h1 align='center'>Schools</h1>
  <div class="row">
    <div class="col-md-8">
      <% @pages.each do |page| %>
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to page.name, page %>
            </h4>
          </div>
        </div>
      <% end %>
    </div>
  </div>  
</div>

<div id = 'box_2'>
  <h2 align='center'>Peek a bit!</h2>
</div>

app/views/pages/new.html.erb
<div id='box_3'>
<h1>New School</h1>

<div class='row'>
  <div class = 'col-md-2'>
    <p>Guidelines</p>
    <ul>
      <li>Use markdown syntax if necessary to write your content.</li>
      <li>Seperate the sections by
      <li>Include the Sections you specify within the Sections field within the black editor</li>
      <li>It would be easier to use the fullscreen option of the editor</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @page do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter school name" %>
      </div>
      <div class="form-group">
        <%= f.label :sections %>
        <%= f.text_area :sections, class: 'form-control', placeholder: "Enter section names." %>
      </div>
      <p>Powered by: <img src="http://epiceditor.com/docs/images/epiceditor-logo.png" alt="EpicEditor"></p>  
      <div id = 'box_4'>
        <div id="epiceditor">
          <%= f.text_area :body, id: 'edit-area' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "Create School info", class: 'btn btn-success', id: 'editor-submit' %>
      </div>
    <% end %>
  </div>
</div>
</div>

<!--<script>
  document.getElementByValue("Create School info").onclick = function () {
  $("#body").value = editor.getElement('editor').body.innerHTML(); // Returns the editor's content
}
</script>-->

<!--<script>
  $('#editor-submit').on('click', function {
  value = $('epiceditor #body').innerHTML();
  body = $('edit-area');
  body.val(value);
}
</script>-->

app/views/pages/show.html.erb
<h1><%= markdown @page.name %></h1> 
<div class='jumbotron'>
    <% @sections.each_with_index do |section, index| %>
      <% secNo = index + 1 %>
      <a href ="<%= index %>"><%= secNo.to_s + "  " + section %></a><br>
    <% end %>
</div>
<p><%= markdown @page.body %></p>